name: list-commits

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: update-tag
        uses: mistermaxis/update-tag-action@output-changelog
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prefix: v
          bump: minor
          suffix: ''
