name: List Commits

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Update Tag
      id: update-tag
      uses: mistermaxis/update-tag-action@output-changelog
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        prefix: v
        bump: minor
        suffix: ''
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.update-tag.outputs.updated_tag }}
        name: Release ${{ steps.update-tag.outputs.updated_tag }}
        body: ${{ steps.update-tag.outputs.changelog }}
        generateReleaseNotes: true
        makeLatest: true
