name: list-commits

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: update-tag
      id: update-tag
      uses: mistermaxis/update-tag-action@output-changelog
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        prefix: v
        bump: minor
        suffix: ''
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.update_tag.outputs.updated_tag }}
        name: Release ${{ steps.update_tag.outputs.updated_tag }}
        makeLatest: true
